#!/usr/bin/env bash

cd $(dirname $(readlink -f $0))

cp kafka-shell /usr/local/bin
cp .kafka-shell-rcscript /usr/local/lib/libkafka-shell

echo 'LIB_FILE=/usr/local/lib/libkafka-shell' > /usr/local/etc/kafka-shell/config
echo 'KAFKA_BINDIR=/usr/local/opt/kafka/bin' >> /usr/local/etc/kafka-shell/config

echo -e ' \033[32m*\033[0m Done'

# vim: sw=4 ts=4 et
